### PR TITLE
Add Maven Information

### PR DESCRIPTION
**Pull request by pmouawad**
Add Maven information to Plugin Manager

### CODE REVIEW

**Comment by pmouawad** [comment]
PR merged as requested

**Comment by undera** [comment]
Ok, now we see that the code you add is not covered with unit test. Please write a unit test covering it (or improve existing test if this is straightforward and has no side effects).

**Comment by pmouawad** [comment]
Hi @undera ,
Original method I modified didn't have JUnit tests :-)
Still I modified one to add tests.

Regards
Philippe M.

**Comment by undera** [comment]
Thanks!

**Pull request merged**
