### PR TITLE
Convert logo from .png to .svg

### PR DESCRIPTION
**Pull request by weisJ**
With higher screen resolution the current resolution of the icon looked very pixelated.
By loading the icon in `svg` format it's ensured that the icon will always be the correct resolution for the monitor.

### CODE REVIEW

**Comment by pmouawad** [comment]
Hello @weisJ ,
Thanks for your contribution.
Did you test this PR with another LAF than Darklaf ?  Does it work with System LAF , Nimbus ..

Thanks

**Comment by weisJ** [comment]
It works with any Laf. The implementation of `darklaf-property-loader` is independent of the Darklaf LaF.

**Comment by undera** [comment]
Did you test this change with clean JMeter installation and adding this new-version plugins manager to it?
What worries me is the new library dependency. Pmgr was always aiming at as few dependencies as possible. Adding whole library to dependencies just because of icon look is questionable for me.

**Comment by weisJ** [comment]
> Did you test this change with clean JMeter installation and adding this new-version plugins manager to it?

I did. Did not experience any issues (in all LaFs).

> What worries me is the new library dependency. Pmgr was always aiming at as few dependencies as possible. Adding whole library to dependencies just because of icon look is questionable for me.

`darklaf-property-loader` is already included in JMeter, so this doesn't effectively add any new dependency.
@pmouawad Maybe JMeter could offer a public api for plugin creators to load svg icons?

**Comment by undera** [comment]
Any new API from JMeter won't help, since pmgr has to support older JMeter versions. You can look at  https://jmeter-plugins.org/stats/ and see all versions that have considerable audience. New function has to work for them. Did you test it with version 3.1?

**Comment by weisJ** [comment]
I had to adjust shade configuration but it works fine on JMeter 3.1

**Comment by undera** [comment]
If it works on 3.1 - then we're good.

**Comment by weisJ** [comment]
I have updated the PR to only load the icon as `svg` if the necessary classes are available (i.e. JMeter 5.3+ is used).

**Comment by undera** [comment]
Looks good

**Pull request merged**
